spring:
  application:
    name: prop-manager
  # DEFAULT (Used if no profile is active)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  # DEV - Let Hibernate manage schema, PROD - Let Liquibase
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
---
# DOCKER PROFILE (Overrides the above when active)
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:propmanager}
    username: ${POSTGRES_USER:propmanager}
    password: ${POSTGRES_PASSWORD:propmanager}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
